name: Validate K8s Api Versions Prod Europe

on:
  workflow_call:
    inputs:
      CLUSTER_ENV:
        required: true
        type: string
        description: Cluster environment (ex. prod)
      CLUSTER_LOCATION:
        required: true
        type: string
        description: Cluster location (ex. europe)
      ZONE:
        required: true
        type: string
        description: Zone of the Google Cloud cluster (ex. europe-west3-b)
      RUNNER:
        required: true
        type: string
        description: Github runner name
      REF:
        required: true
        type: string
        default: ${{ github.ref }}
        description: Branch/Commit/Tag to checkout
    secrets:
      GCP_SA_KEY:
        required: true
        description: Google cloud github action service account key

jobs:
  validate:
    name: Validate K8s Api Versions
    runs-on: ${{ inputs.RUNNER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ inputs.REF }}

      - name: GCloud Authentification
        uses: google-github-actions/auth@v0.8.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get Cluster Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ inputs.CLUSTER_ENV }}-${{ inputs.CLUSTER_LOCATION }}
          location: ${{ inputs.ZONE }}

      - name: Install Helm
        uses: azure/setup-helm@v3.4
        with:
          version: 3.9.0

      - name: Install Map Kube Apis
        run: |
          helm plugin install https://github.com/helm/helm-mapkubeapis
        continue-on-error: true

      - name: Test Api Versions
        run: |
          ./scripts/k8s_apis_validation
