name: Docker Build Template

on:
  workflow_call:
    inputs:
      REF:
        required: true
        type: string
      GCR_HOSTNAME:
        required: true
        type: string
      GCP_PROJECT:
        required: true
        type: string
      IMAGE:
        required: true
        type: string
      BUILD_VERSION:
        required: true
        type: string
      BUILD_ARGS:
        required: false
        type: string
      DOCKERFILE_PATH:
        required: false
        type: string
    secrets:
      GCP_SA_KEY:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.REF }}

      - name: GCloud Authentification
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Google Cloud Docker Auth
        run: |-
          gcloud auth configure-docker

      - name: Build Dockerops Docker Image
        run: |
          docker build -t ${{ inputs.GCR_HOSTNAME }}/${{ inputs.GCP_PROJECT }}/${{ inputs.IMAGE }}:${{ inputs.BUILD_VERSION }} ${{ inputs.BUILD_ARGS }} ${{ inputs.DOCKERFILE_PATH }} .

      - name: Push Docker Image
        run: |
          docker push  ${{ inputs.GCR_HOSTNAME }}/${{ inputs.GCP_PROJECT }}/${{ inputs.IMAGE }}:${{ inputs.BUILD_VERSION }}