name: Prevent Drift Template

on:
  workflow_call:
    inputs:
      CLUSTER_ENV:
        required: true
        type: string
        description: Cluster environment (ex. prod)
      CLUSTER_LOCATION:
        required: true
        type: string
        description: Cluster location (ex. europe)
      RUNNER:
        required: true
        type: string
        description: Github runner name
      REF:
        required: true
        type: string
        description: Branch/Commit/Tag to checkout
    secrets:
      GCP_SA_KEY:
        required: true
        description: Google cloud github action service account key
      GH_CI_CD_TOKEN:
        required: true
        description: GitHub - De Marque CI/CD aka Jenkins personnal access tokens (classic)
      SLACK_WEBHOOK_URL:
        required: true
        description: Product slack webhook url

jobs:
  prevent-drift:
    name: Prevent Drift
    runs-on: ${{ inputs.RUNNER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ inputs.REF }}

      - name: GCloud Authentification
        uses: google-github-actions/auth@v0.8.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Prepare credentials
        run: |
          mkdir -p creds
          ln -s $GOOGLE_APPLICATION_CREDENTIALS creds/serviceaccount.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.2.3

      - name: Terraform Init
        id: init
        run: |
          cd environments/${{ inputs.CLUSTER_ENV }}/${{ inputs.CLUSTER_LOCATION }} || cd ${{ inputs.CLUSTER_ENV }}/${{ inputs.CLUSTER_LOCATION }}
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd environments/${{ inputs.CLUSTER_ENV }}/${{ inputs.CLUSTER_LOCATION }} || cd ${{ inputs.CLUSTER_ENV }}/${{ inputs.CLUSTER_LOCATION }}
          terraform plan -detailed-exitcode -no-color -out ${{ inputs.CLUSTER_ENV }}-${{ inputs.CLUSTER_LOCATION }}.out -var-file=${{ inputs.CLUSTER_ENV }}-${{ inputs.CLUSTER_LOCATION }}.tfvars -lock-timeout=500s

  finalize:
    name: Finalize
    runs-on: ubuntu-latest
    needs: prevent-drift
    if: ${{ failure() }}

    steps:
      - name: Fetch Workflow Conclusion
        uses: technote-space/workflow-conclusion-action@v3.0.2

      - name: Notify
        uses: 8398a7/action-slack@v3.14.0
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_CD_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
