name: Automerge

on:
  workflow_call:
    secrets:
      GH_CI_CD_TOKEN:
        required: true
        description: GitHub - De Marque CI/CD aka Jenkins personnal access tokens (classic)

jobs:
  automerge:
    runs-on: ubuntu-22.04
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_CD_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-description
          MERGE_FORKS: false
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000
          UPDATE_LABELS: automerge
          UPDATE_METHOD: merge
