name: Deploy Template

on:
  workflow_call:
    inputs:
      CLUSTER_ENV:
        required: true
        type: string
        description: Cluster environment (ex. prod)
      CLUSTER_LOCATION:
        required: true
        type: string
        description: Cluster location (ex. europe)
      MODULE_ROOT:
        required: true
        type: string
        description: Module root in demarque-infra
      MODULE_NAME:
        required: true
        type: string
        description: Module name in demarque-infra
      TARGETS:
        required: true
        type: string
        description: Terraform targets to deploy split by comma (ex. helm_release.firehose, kubernetes_config_map.firehose_vector_config)
      RUNNER:
        required: true
        type: string
        description: Github runner name
      REF:
        required: false
        type: string
        default: ${{ github.ref }}
        description: Branch/Commit/Tag to checkout
    secrets:
      GCP_SA_KEY:
        required: true
        description: Google cloud github action service account key
      GH_CI_CD_TOKEN:
        required: true
        description: GitHub - De Marque CI/CD aka Jenkins personnal access tokens (classic)
      SLACK_WEBHOOK_URL:
        required: true
        description: Product slack webhook url

jobs:
  terraform:
    name: Terraform
    runs-on: ${{ inputs.RUNNER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ inputs.REF }}

      - name: GCloud Authentification
        uses: google-github-actions/auth@v0.8.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Prepare credentials
        run: |
          mkdir -p creds
          ln -s $GOOGLE_APPLICATION_CREDENTIALS creds/serviceaccount.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.3.3

      - name: Buil targets
        id: build_target
        run: |
          BUILDED_TARGETS=`echo ${{ inputs.TARGETS }} | sed -r 's/[, ]+/ -target module.${{ inputs.MODULE_ROOT }}-${{ inputs.MODULE_NAME }}./g' | sed -r 's/^/-target module.${{ inputs.MODULE_ROOT }}-${{ inputs.MODULE_NAME }}./g'`
          echo "Deploying with targets: ${BUILDED_TARGETS}"
          echo "BUILDED_TARGETS=${BUILDED_TARGETS}" >> $GITHUB_OUTPUT

      - name: Terraform Init
        id: init
        run: |
          cd environments/${{ inputs.CLUSTER_ENV }}/${{ inputs.CLUSTER_LOCATION }}
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd environments/${{ inputs.CLUSTER_ENV }}/${{ inputs.CLUSTER_LOCATION }}
          terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: |
          cd environments/${{ inputs.CLUSTER_ENV }}/${{ inputs.CLUSTER_LOCATION }}
          terraform apply -no-color -auto-approve -var-file=${{ inputs.CLUSTER_ENV }}-${{ inputs.CLUSTER_LOCATION }}.tfvars -lock-timeout=500s ${{ steps.build_target.outputs.BUILDED_TARGETS }}

  finalize:
    name: Finalize
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ always() }}

    steps:
      - name: Fetch Workflow Conclusion
        uses: technote-space/workflow-conclusion-action@v3.0.2

      - name: Notify
        uses: 8398a7/action-slack@v3.14.0
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_CD_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
