name: Docker Build Template

on:
  workflow_call:
    inputs:
      REF:
        required: false
        type: string
        default: ${{ github.ref }}
        description: Branch/Commit/Tag to checkout
      GCR_HOSTNAME:
        required: true
        type: string
        description: Google cloud registry hostname (ex. gcr.io|eu.gcr.io)
      GCP_PROJECT:
        required: true
        type: string
        description: Google cloud project (ex. demarque)
      IMAGE:
        required: true
        type: string
        description: Docker image name
      BUILD_VERSION:
        required: true
        type: string
        description: Docker version tag
      BUILD_ARGS:
        required: false
        type: string
        description: Docker build arguments (ex. --build-arg ARGUMENT=ARGUMENT)
      DOCKERFILE_PATH:
        required: false
        type: string
        description: Dockerfil path (ex. -f docker/Dockerfile)
    secrets:
      GCP_SA_KEY:
        required: true
        description: Google cloud github action service account key

concurrency:
  group: ${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ inputs.REF }}

      - name: GCloud Authentification
        uses: google-github-actions/auth@v0.8.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Google Cloud Docker Auth
        run: |-
          gcloud auth configure-docker

      - name: Build Dockerops Docker Image
        run: |
          docker build -t ${{ inputs.GCR_HOSTNAME }}/${{ inputs.GCP_PROJECT }}/${{ inputs.IMAGE }}:${{ inputs.BUILD_VERSION }} ${{ inputs.BUILD_ARGS }} ${{ inputs.DOCKERFILE_PATH }} .

      - name: Push Docker Image
        run: |
          docker push  ${{ inputs.GCR_HOSTNAME }}/${{ inputs.GCP_PROJECT }}/${{ inputs.IMAGE }}:${{ inputs.BUILD_VERSION }}