name: Backup Helm Charts template

on:
  workflow_call:
    inputs:
      REPOSITORY:
        required: false
        type: string
        default: ${{ github.repository }}
        description: Repository to checkout before the build
      REF:
        required: false
        type: string
        default: ${{ github.ref }}
        description: Branch/Commit/Tag to checkout
      EVENTBUS_DEPLOY:
        required: false
        type: boolean
        default: false
        description: Define if we need to populate ssh-agent with Eventbus
    secrets:
      GCP_SA_KEY:
        required: true
        description: Google cloud github action service account key
      GH_CI_CD_TOKEN:
        required: true
        description: GitHub - De Marque CI/CD aka Jenkins personnal access tokens (classic)
      SLACK_WEBHOOK_URL:
        required: true
        description: Product slack webhook url

jobs:
  push-helm-charts:
    name: Push Helm Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
        with:
          repository: ${{ inputs.REPOSITORY }}
          ref: ${{ inputs.REF }}

      - name: GCloud Authentification
        uses: google-github-actions/auth@v0.8.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Google Cloud Docker Auth
        run: |-
          gcloud auth configure-docker

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip

      - name: Install Python Dependencies
        run: pip install -r scripts/helm-charts-registry/requirements.txt

      - name: Push Helm Charts
        run: python3 scripts/helm-charts-registry/fetch_helm_charts.py

  finalize:
    name: Finalize
    runs-on: ubuntu-latest
    needs: push-helm-charts
    if: ${{ failure() }}

    steps:
      - name: Fetch Workflow Conclusion
        uses: technote-space/workflow-conclusion-action@v3.0.2

      - name: Notify
        uses: 8398a7/action-slack@v3.14.0
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_CD_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
